title: Fort Lauderdale Mortgage Video Blog with Dagoberto Castillo
description: Our mission at NEXA Mortgage, LLC is to be your best resource for Mortgage advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about Mortgages. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from First Step Home Loans.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Dagoberto Castillo
  title: 
  license_number: Licensed Mortgage Loan Originator - NMLS# 385009
  about_markdown: |
     Faithful husband & dad. Habitual walker & reader. Coach & career consultant for Realtors and loan originators. More than 15 years experience in the real estate and mortgage industries. I am the professional mortgage loan originator you can trust for all your mortgage needs throughout the state of Florida.
  brand: 
  brokerage:
  market: Fort Lauderdale, FL
  address: Call / Text / WhatsApp
  phone: 954-271-2995
  phone_type:
  phone2:
  phone2_type:
  email:
  url: http://ObtainAmortgage.com

forms:
  sitekey:

CTAs:
  first_CTA_text: Sign In Today for Your Loan Application 
  first_CTA_URL: https://1660690.my1003app.com/385009/register
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/002.jpg
    CTA_title: "Apply For A Loan"
    CTA_text: "Sign In Today for Your Loan Application"
    CTA_link_text: "Create Account"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- market -- Home?"
    CTA_text2: "Search the entire MLS for your -- market -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
  google_business_url:

podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- client brand -- - your professional -- market -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- market --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- client name --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: 
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
  header_overlay: rgba(0, 0, 0, 0.3)

site_colors:
  brand_color: '#262262'
  theme_color: '#636363'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
